export const navItems = [
  { label: "Find Jobs", active: true },
  { label: "Top Companies" },
  { label: "Job Tracker" },
  { label: "My Calendar" },
  { label: "Documents" },
  { label: "Messages" },
  { label: "Notifications" },
];

export const jobTypesOptions = [
  { label: "Select Type", value: "" },
  { label: "Full Time", value: "Full Time" },
  { label: "Part Time", value: "Part Time" },
  { label: "Find Jobs", value: "Find Jobs" },
];

export const locationOptions = [
  { label: "Select Location", value: "" },
  { label: "Seattle", value: "Seattle" },
  { label: "New York", value: "New York" },
  { label: "Remote", value: "Remote" },
];

export const jobTags = ["Frontend", "Backend", "Graphic Designer"];

export const featuredJobs = [
  {
    id: "feat-1",
    jobStack: "Graphic Designer",
    jobType: "Contract",
    promoted: true,
    title: "UI/UX Designer",
    company: "Teams",
    location: "Seattle, USA (Remote)",
    timeAgo: "1 day ago",
    applicants: "22 applicants",
  },
  {
    id: "feat-2",
    jobStack: "Backend",
    jobType: "Contract",
    promoted: true,
    title: "Product Designer",
    company: "Slack",
    location: "New York, USA",
    timeAgo: "2 days ago",
    applicants: "18 applicants",
  },
  {
    id: "feat-3",
    jobStack: "Frontend",
    jobType: "Full Time",
    promoted: true,
    title: "Frontend Developer",
    company: "Google",
    location: "California, USA (Hybrid)",
    timeAgo: "3 days ago",
    applicants: "35 applicants",
  },
  {
    id: "feat-4",
    jobStack: "Frontend",
    jobType: "Contract",
    promoted: true,
    title: "App Designer",
    company: "Airbnb",
    location: "Remote",
    timeAgo: "4 days ago",
    applicants: "12 applicants",
  },
  {
    id: "feat-5",
    jobStack: "Backend",
    jobType: "Full Time",
    promoted: true,
    title: "Designer",
    company: "Figma",
    location: "Remote",
    timeAgo: "5 days ago",
    applicants: "29 applicants",
  },
  {
    id: "feat-6",
    jobStack: "Frontend",
    jobType: "Part Time",
    promoted: true,
    title: "UX Researcher",
    company: "Meta",
    location: "Austin, USA",
    timeAgo: "6 days ago",
    applicants: "16 applicants",
  },
];

export const recommendedJobs = [
  {
    id: "rec-1",
    jobStack: "Frontend",
    jobType: "Part Time",
    promoted: false,
    title: "Backend Developer",
    company: "Teams",
    location: "Remote",
    timeAgo: "1 day ago",
    applicants: "27 applicants",
  },
  {
    id: "rec-2",
    jobStack: "Frontend",
    jobType: "Contract",
    promoted: false,
    title: "React Developer",
    company: "Netflix",
    location: "Remote",
    timeAgo: "2 days ago",
    applicants: "41 applicants",
  },
  {
    id: "rec-3",
    jobStack: "Graphic Designer",
    jobType: "Full Time",
    promoted: false,
    title: "Node.js Developer",
    company: "Amazon",
    location: "Remote",
    timeAgo: "3 days ago",
    applicants: "33 applicants",
  },
  {
    id: "rec-4",
    jobStack: "Frontend",
    jobType: "Contract",
    promoted: false,
    title: "Full Stack",
    company: "Spotify",
    location: "Seattle, USA (Remote)",
    timeAgo: "4 days ago",
    applicants: "19 applicants",
  },
  {
    id: "rec-5",
    jobStack: "Graphic Designer",
    jobType: "Contract",
    promoted: false,
    title: "Java Developer",
    company: "Adobe",
    location: "Remote",
    timeAgo: "5 days ago",
    applicants: "24 applicants",
  },
  {
    id: "rec-6",
    jobStack: "Frontend",
    jobType: "Contract",
    promoted: false,
    title: "SQA",
    company: "Microsoft",
    location: "Seattle, USA (Remote)",
    timeAgo: "6 days ago",
    applicants: "38 applicants",
  },
  {
    id: "rec-7",
    jobStack: "Backend",
    jobType: "Full Time",
    promoted: false,
    title: "Engineer",
    company: "Stripe",
    location: "Remote",
    timeAgo: "7 days ago",
    applicants: "45 applicants",
  },
];

export const latestJobs = [
  {
    id: "lat-1",
    jobStack: "Frontend",
    jobType: "Part Time",
    promoted: false,
    title: "Backend Developer",
    company: "Teams",
    location: "Remote",
    timeAgo: "1 day ago",
    applicants: "27 applicants",
  },
  {
    id: "lat-2",
    jobStack: "Frontend",
    jobType: "Contract",
    promoted: false,
    title: "React Developer",
    company: "Netflix",
    location: "Remote",
    timeAgo: "2 days ago",
    applicants: "41 applicants",
  },
  {
    id: "lat-3",
    jobStack: "Graphic Designer",
    jobType: "Full Time",
    promoted: false,
    title: "Node.js Developer",
    company: "Amazon",
    location: "Remote",
    timeAgo: "3 days ago",
    applicants: "33 applicants",
  },
];
